version: '3'
services:
  movies:
    image: vemula7777/trainrepo:latest
    ports:
      - "30:80"
    deploy:
      replicas: 2

  train:
    image: vemula7777/moviesrepo:latest
    ports:
      - "31:80"
    deploy:
      replicas: 2

  dth:
    image: vemula7777/todaydth:latest
    ports:
      - "32:80"
    deploy:
      replicas: 2

  recharge:
    image: vemula7777/todayrecharge:latest
    ports:
      - "33:80"
    deploy:
      replicas: 2
